version: '3.3'

services:
  app-server-django:
    build: ./
    command: >
      sh -c "python manage.py flush --no-input &&
           python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
