# Generated by Django 4.0.1 on 2022-01-30 10:31

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_biography_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
